<?php
require_once 'PHPUnit/Framework.php';

/**
 * Test class for Phergie_Plugin_Pong.
 * Generated by PHPUnit on 2010-03-20 at 14:04:28.
 */
class Phergie_Plugin_PongTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Phergie_Plugin_Pong
     */
    protected $object;
    /**
     * @var Phergie_Event_Handler
     */
    protected $handler;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $connection = new Phergie_Connection();
        $this->handler = new Phergie_Event_Handler();
        $this->object = new Phergie_Plugin_Pong;
        $this->object->setEventHandler($this->handler);
        $this->object->setConnection($connection);
        $event = new Phergie_Event_Request();
        $event->setType(Phergie_Event_Request::TYPE_PING);
        $this->object->setEvent($event);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * Test that when a ping is received, a Phergie_Event_Command::TYPE_PONG
     * is set to the handler
     */
    public function testOnPing()
    {
        $this->object->onPing();
        $this->assertTrue($this->handler->hasEventOfType(Phergie_Event_Command::TYPE_PONG));
    }
}